version: '3.8'
services:
  mongodb:
    image: 'mongo'
    volumes:
      - mongo-data:/data/db
    env_file:
      - ./.env.local
  back:
    depends_on:
      - mongodb
    image: 'ics-back-dev'
    build: ./
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env.local
volumes:
  mongo-data:
