name: CI interactive comments section
run-name: ${{ github.actor }} is activating CI

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.15.0]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run eslint
        run: npx lint-staged

      - name: Run unit tests
        run: npm run test

      - name: Run build
        run: npm run build
