name: CI interactive comments section workflow
run-name: ${{ github.actor }} is activating CI process

on:
  pull_request:
    branches:
      - dev

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  lint:
    name: Run linter
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run eslint
        run: npx lint-staged

  unit-test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

  build:
    name: Run build application
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
