name: CI interactive comments section
run-name: ${{ github.actor }} is activating CI

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  lint:
    name: Run linter
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run eslint
        run: npx lint-staged

  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

  build:
    name: Run build application
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
